### ISSUE TITLE
Removing global plugins does not remove features from editor

### ISSUE THREAD

**Issue by ian-datto** [froala/Craft-3-Froala-WYSIWYG#3]
Removing plugins globally from `Enabled Plugins` page does not remove them from the Craft entry field and are still available.

**Comment by bertoost** [comment]
Any pluging? Or do you have specific examples?

**Comment by ian-datto** [comment]
Any plugin. If removed globally they still appear in the channel field.

For example, disabling the 'Font Family' plugin globally from `Enabled Plugins` does not remove it from the editor.

**Comment by bertoost** [comment]
Thanks to clear this out. I will investigate it asap.

**Comment by bertoost** [comment]
I found the issue. Will be fixed in the next RC update (hopefully later on today)
