### ISSUE TITLE
Plugin does not generate a config folder or example .json files for Custom Editor Config

### ISSUE THREAD

**Issue by ian-datto** [froala/Craft-3-Froala-WYSIWYG#4]
No config folder is located at `var/craft/config/froalaeditor/` and no examples of required JSON formatting or file naming conventions are provided

**Comment by bertoost** [comment]
The plug-in will and can’t create an example folder in your installation.. I can provide some config examples on the repository.

You should create it yourself and you should use normal json formatted file like;

{
    “Key”: “value”,
    “AnotherKey”: “value”
}

You can use all the options from the Froala site in your custom configs.

**Comment by bertoost** [comment]
I have added an example json file to the repository, so you can have an idea about how this works.
